CREATE TABLE EVN_CALENDARS (
    CAL_ID int primary key,
    CAL_INFO_CD timestamp not null,
    CAL_INFO_RD timestamp,
    CAL_USR_ID int,
    CAL_MOV_ID int,
    CAL_CIN_ID int,
    CAL_DATE timestamp not null,
    CAL_TIME int,
    FOREIGN KEY (CAL_USR_ID) REFERENCES USR_USERS(USR_ID),
    FOREIGN KEY (CAL_MOV_ID) REFERENCES MOV_MOVIES(MOV_ID),
    FOREIGN KEY (CAL_CIN_ID) REFERENCES MOV_CINEMAS(CIN_ID)
);

CREATE TABLE EVN_NOTIFICATIONS (
    NOT_ID int primary key,
    NOT_USR_ID int,
    NOT_STATUS varchar(1) not null,
    NOT_TYPE varchar(1) not null,
    NOT_DATE timestamp,
    NOT_DESCRIPTION text,
    FOREIGN KEY (NOT_USR_ID) REFERENCES USR_USERS(USR_ID)
);

CREATE TABLE EVN_EVENTS (
   EVN_ID int primary key,
   EVN_INFO_CD timestamp not null,
   EVN_INFO_CU int not null,
   EVN_INFO_RD timestamp,
   EVN_INFO_RU int,
   EVN_NAME varchar(100),
   EVN_DESCRIPTION varchar(500),
   EVN_STATUS varchar(1) not null,
   EVN_MOV_ID int,
   EVN_CIN_ID int,
   EVN_OWNER_ID int,
   EVN_OPEN boolean,
   EVN_MAX_PARTICIPANTS int,
   FOREIGN KEY (EVN_INFO_CU) REFERENCES USR_USERS(USR_ID),
   FOREIGN KEY (EVN_INFO_RU) REFERENCES USR_USERS(USR_ID),
   FOREIGN KEY (EVN_MOV_ID) REFERENCES MOV_MOVIES(MOV_ID),
   FOREIGN KEY (EVN_CIN_ID) REFERENCES MOV_CINEMAS(CIN_ID),
   FOREIGN KEY (EVN_OWNER_ID) REFERENCES USR_USERS(USR_ID)
);

CREATE SEQUENCE seq_evn_cal_id
    MINVALUE 50
    START WITH 50
    INCREMENT BY 50
    CACHE 10;

CREATE SEQUENCE seq_evn_not_id
    MINVALUE 50
    START WITH 50
    INCREMENT BY 50
    CACHE 10;

CREATE SEQUENCE seq_evn_id
    MINVALUE 50
    START WITH 50
    INCREMENT BY 50
    CACHE 10;