ALTER TABLE USR_ROLES
RENAME TO SYS_ROLES;

ALTER TABLE SYS_ROLES
DROP COlUMN ROL_USR_ID;

CREATE TABLE USR_USR_ROLES (
    ROL_ID int,
    USR_ID int,
    CONSTRAINT ROL_USR_PK PRIMARY KEY (ROL_ID, USR_ID),
    CONSTRAINT ROL_FK FOREIGN KEY (ROL_ID) REFERENCES SYS_ROLES (ROL_ID),
    CONSTRAINT USR_FK FOREIGN KEY (USR_ID) REFERENCES USR_USERS (USR_ID)
);
