CREATE TABLE USERS_REVIEWS(
      URV_ID int,
      USR_ID int,
      CONSTRAINT ROL_USR_PK PRIMARY KEY (URV_ID, USR_ID),
      CONSTRAINT ROL_FK FOREIGN KEY (URV_ID) REFERENCES USR_REVIEWS (URV_ID),
      CONSTRAINT USR_FK FOREIGN KEY (USR_ID) REFERENCES USR_USERS (USR_ID)
);
