CREATE TABLE USR_USR_REVIEWS(
      URV_ID int,
      USR_ID int,
      CONSTRAINT URR_USR_PK PRIMARY KEY (URV_ID, USR_ID),
      CONSTRAINT URR_URV_FK FOREIGN KEY (URV_ID) REFERENCES USR_REVIEWS (URV_ID),
      CONSTRAINT URR_FK FOREIGN KEY (USR_ID) REFERENCES USR_USERS (USR_ID)
);
