ALTER TABLE MOV_ACTORS ALTER COLUMN ACT_INFO_RD DROP NOT NULL;
ALTER TABLE MOV_MOVIES ALTER COLUMN MOV_INFO_RD DROP NOT NULL;
ALTER TABLE USR_COMMENTS ALTER COLUMN UCM_INFO_RU DROP NOT NULL;
ALTER TABLE USR_REPORTS ALTER COLUMN REP_INFO_RU DROP NOT NULL;
ALTER TABLE USR_REVIEWS ALTER COLUMN URV_INFO_RU DROP NOT NULL;
ALTER TABLE USR_USERS ALTER COLUMN USR_TIER_ID DROP NOT NULL;