INSERT INTO SYS_DICTIONARIES(dic_id, dic_domain) VALUES (nextval('seq_sys_dic_id'), 'API_URLS');
INSERT INTO SYS_DICTIONARIES(dic_id, dic_domain) VALUES (nextval('seq_sys_dic_id'), 'EMAIL_CONFIGURATION');


INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'ACTIVATE_TITLE', 'Confirm your email', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'EMAIL_CONFIGURATION'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'ACTIVATE_MESSAGE', 'Welcome in Cinema Club!<br/>Please activate your account by clicking the following link:<br/>', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'EMAIL_CONFIGURATION'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'PWD_RESET_TITLE', 'Change your password', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'EMAIL_CONFIGURATION'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'PWD_RESET_MESSAGE', 'Welcome in Cinema Club!<br/>Change your password by clicking the following link:<br/>', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'EMAIL_CONFIGURATION'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'MOVIES_API_URL', 'https://api.themoviedb.org/3/movie/{{QUERY}}?{{MOVIES_API_KEY}}&{{MOVIES_API_LANGUAGE}}', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'MOVIES_API_URL_QUERY', 'https://api.themoviedb.org/3/search/movie?query={{query}}&{{MOVIES_API_KEY}}&{{MOVIES_API_LANGUAGE}}', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'MOVIES_API_KEY', 'api_key=08529ee2a8448b81018b7519148033ed&', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'MOVIES_API_LANGUAGE', 'language=en-US', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'MOVIES_API_URL_TOP_RATED', 'https://api.themoviedb.org/3/movie/top_rated?{{MOVIES_API_KEY}}', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'MOVIES_API_URL_MOST_POPULAR', 'https://api.themoviedb.org/3/movie/popular?{{MOVIES_API_KEY}}', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'NYT_API_URL', 'https://api.nytimes.com/svc/movies/v2/reviews/picks.json?{{NYT_API_KEY}}', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'NYT_API_URL_QUERY', 'https://api.nytimes.com/svc/movies/v2/reviews/search.json?query={{QUERY}}&{{NYT_API_KEY}}', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'NYT_API_KEY', 'api-key=iDAhRto0lVh4h1FAhnLiYTHjHePGWVLL', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'GUARDIAN_API_URL', 'https://content.guardianapis.com/', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'GUARDIAN_API_URL_QUERY', 'https://content.guardianapis.com/search?q={{QUERY}} review&{{GUARDIAN_API_KEY}}&show-fields=byline,trailText', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
INSERT INTO SYS_DIC_ITEMS(dit_id, dit_info_cd, dit_name, dit_value, dit_dic_id) VALUES (nextval('seq_sys_dit_id'), CURRENT_TIMESTAMP, 'GUARDIAN_API_KEY', 'api-key=5ecfbb08-6408-46ca-aa33-60985a0f1f83', (SELECT DIC_ID FROM sys_dictionaries WHERE dic_domain = 'API_URLS'));
